# Generated by Django 3.2.9 on 2021-11-11 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preferences',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user', verbose_name='user')),
                ('galaxy', models.BooleanField(default=True)),
                ('stars', models.BooleanField(default=True)),
                ('planets', models.BooleanField(default=True)),
                ('blackHoles', models.BooleanField(default=True)),
                ('moons', models.BooleanField(default=True)),
            ],
        ),
    ]
