# Generated by Django 3.2.9 on 2021-11-11 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='preferences',
            old_name='galaxy',
            new_name='galaxies',
        ),
    ]
